### ISSUE TITLE
Autocomplete reference duplicates label

### ISSUE THREAD

**Issue by dpo** [ashthespy/Atom-LaTeX#186]
For a little while now I've been observing the following autocomplete behavior. I set my labels in the form `eq:my-equation` for equations, `fig:my-figure` for figures, etc.

If I type `\eqref{`, the autocomplete dropdown shows up, I then type `eq` (without typing a colon), select a label, hit tab, and I get the correct completion.

However, if I type `eq:` **with a colon** and select the label I'm interested in (say `eq:my-equation`), the completion ends up being `\eqref{eq:eq:my-equation}` instead of just `\eqref{eq:my-equation}`. 

The moment I type `:`, the autocomplete pulldown visibly shifts to the right, so it seems like something is happening.

Has anyone else observed this? I only have official autocomplete packages installed and no other autocomplete package related to LaTeX.

Thanks!

![atom-latex](https://user-images.githubusercontent.com/38760/49812585-b8c6dd00-fd33-11e8-9dcf-68540df25151.gif)

**Comment by dpo** [comment]
Bump. Can anyone reproduce this? I opened a Discourse discussion here, which may contain leads to resolve the problem: 
https://discuss.atom.io/t/autocomplete-reference-duplicates-label-in-latex-documents/62015

Thanks!

**Comment by ashthespy** [comment]
@dpo I typed out a response back then but apparently dind't hit comment!

I to have the same issue, but after a (not through) investigation pinned the blame on the upstream Atom's own `autocomplete-plus` package that we use via the [provider API](https://github.com/atom/autocomplete-plus/wiki/Provider-API). 
At the time, I skimmed through the `autocomplete-plus` issues but didn't find anything striking. I will investigate more, and maybe open up an issue in their repo for guidance.

**Comment by dpo** [comment]
Great news! Thanks!

**Comment by ashthespy** [comment]
@dpo It does look like an issue with the `nonWordCharacters` - but will take some more investigation. Will keep you posted.

**Comment by ashthespy** [comment]
@dpo Try adding `:` to the `Extra Word Characters` setting found under  `autocomplte-plus` package settings. That should fix the issue. I wonder if there a more specific way this.

**Comment by dpo** [comment]
I have tried that already. It doesn't fix the problem for me. Does it fix it for you?

**Comment by ashthespy** [comment]
Yep - just to confirm - this is not the editor `Non Word Characters`.
Before:
![autocomplete_](https://user-images.githubusercontent.com/16233271/51284534-2083de00-19ec-11e9-9b0a-0f3d4ea11c25.gif)
After:
![autocomplete](https://user-images.githubusercontent.com/16233271/51284542-237ece80-19ec-11e9-8927-726567e2ef4b.gif)

**Comment by dpo** [comment]
I tried your suggestion on two computers (both macOS), and it didn't fix the issue on either. Perhaps things are different on other platforms?!

**Comment by ashthespy** [comment]
The issue is being tracked in upstream in `autocomplete-plus` as the from our side we are(99.99%) setting the right parameters for replacement. 

>I tried your suggestion on two computers (both macOS), and it didn't fix the issue on either. Perhaps things are different on other platforms?!

The workaround I mentioned also requires bumping up the provider version to `4.0.0` in [`package.json`](https://github.com/James-Yu/Atom-LaTeX/blob/8188e97ee0f89f3b43c977581aa60d332a12fb50/package.json#L21) - but I would rather wait for something from the `autocomplete-plus` guys before pushing the workaround as a fix.

**Comment by dpo** [comment]
Great, thank you!

**Comment by dpo** [comment]
Just wondering if there are any news here.

**Comment by ashthespy** [comment]
Not really https://github.com/atom/autocomplete-plus/issues/1020#issuecomment-471125376

**Comment by BambOoxX** [comment]
Not sure if this is the same issue, but when typing `\includegraphics{some/path}` I get the same (wrong) behavior. This is quite annoying...

**Comment by ashthespy** [comment]
It's quite irritating I agree, but don't have the time to debug upstream issues at the moment. 
So unless there is some action over at  atom/autocomplete-plus#1020 not much I can do for now.

**Comment by ashthespy** [comment]
@dpo @BambOoxX  Managed to fix this with the following patch

```diff
diff --git a/package.json b/package.json
index 7f0fbec..fe7b306 100644
--- a/package.json
+++ b/package.json
@@ -18,7 +18,7 @@
   "providedServices": {
     "autocomplete.provider": {
       "versions": {
-        "2.0.0": "provide"
+        "4.0.0": "provide"
       }
     }
   },
diff --git a/settings/language-latex.cson b/settings/language-latex.cson
index 9645e98..3c4ebf2 100644
--- a/settings/language-latex.cson
+++ b/settings/language-latex.cson
@@ -4,6 +4,8 @@
     'tabLength': 2
     'softWrap': true
     'commentStart': '% '
+  'autocomplete-plus':
+    'extraWordCharacters': ':_/'
   'bracket-matcher':
     'autocompleteCharacters': [
       '$$',
```
Should find its way into the next release - don't want to push two on the same day ;-)

**Comment by dpo** [comment]
Oh please, please please ;-). That bug bothers me every single day.

**Comment by dpo** [comment]
I have labels with multiple `:` and `-` characters, e.g., `alg:my-algorithm`. If I type `alg:my` and hit `TAB`, the name is now completed correctly. Thank you!

However, if I type `alg:my-` and hit `TAB`, the same problem as before occurs; the entire label is pasted after what I typed. I tried adding `-` to the list of extra non-word characters in `settings/language-latex.cson` but no success... Any ideas?

**Comment by ashthespy** [comment]
@dpo Sorry my notifications are whack these days, but for your case try:
```cson
# This works
'extraWordCharacters': '-:_/'
# This doesn't ¯\_(ツ)_/¯
'extraWordCharacters': ':_/-'
```

**Comment by dpo** [comment]
Finally!!! Thank you!!!

**Comment by dpo** [comment]
Ps: perhaps there should be a setting for `extraWordCharacters`?!
